// SPDX-FileCopyrightText: Ryan Madhuwala [rawx18.dev@gmail.com](mailto:rawx18.dev@gmail.com)
// SPDX-License-Identifier: AGPL-3.0-only
import { spawnSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const backend = fileURLToPath(new URL('../../backend', import.meta.url));
const result = spawnSync('uv', [
  'run', '--project', backend, '--locked', 'python', '-c',
  'import json; from app.main import app; print(json.dumps(app.openapi()))',
], { cwd: backend, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 });
if (result.error || result.status !== 0) {
  throw new Error(`Cannot generate backend contract: ${result.error?.message ?? result.stderr}`);
}
const schema = JSON.parse(result.stdout);
const content = '// SPDX-FileCopyrightText: Ryan Madhuwala [rawx18.dev@gmail.com](mailto:rawx18.dev@gmail.com)\n'
  + '// SPDX-License-Identifier: AGPL-3.0-only\n'
  + '// Generated by npm run contracts from the backend OpenAPI schema.\n\n'
  + astToString(await openapiTS(schema));
const file = new URL('../src/contracts.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(file, 'utf8') !== content) {
    throw new Error('Backend contract differs. Run npm run contracts and review the artifact.');
  }
  console.log('Generated contract matches the backend byte-for-byte.');
} else {
  await writeFile(file, content);
  console.log('Generated src/contracts.ts from backend OpenAPI.');
}